apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-monitor-grafana2
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: grafana2.mda.iba
    http:
      paths:
      - backend:
          service:
            name: system-monitor-grafana2
            port:
              number: 3000
        pathType: ImplementationSpecific
        
